openapi: 3.0.0
info:
  title: User API
  description: Simple API to manage users
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /users:
    $ref: './paths/users.yaml#/users'
  
  /users/{userId}:
    $ref: './paths/user-by-id.yaml#/users-by-id'

components:
  schemas:
    User:
      $ref: './components/schemas/User.yaml'
    
    Error:
      $ref: './components/schemas/Error.yaml'
